# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcc61212428190a52e825e02b679b8115e206adfdf018cfdc399ae6bbbf30bd02a3190498471b0d3ef53723bcb23e85d9d5102cb1d0e81df3bdb13d15345cad5

test:
  secret_key_base: bcae134901889fbf9e3076490381c39a57cfa46cdfa29855b7c8702174b2986d1b883f4509c99163117426579da5c65a1ef663c753126edc374393998366be9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
